"""add_ticket_assignment

Revision ID: 13ee6529f798
Revises: a1b2c3d4e5f6
Create Date: 2026-03-24 18:17:43.933390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13ee6529f798'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    
    op.add_column('tickets', sa.Column('assigned_to_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to_user_id'], ['id'])

    if bind.engine.name == 'postgresql':
        # Create the ENUM type first
        op.execute("CREATE TYPE ticketstatus AS ENUM ('open', 'in_progress', 'resolved', 'closed')")
        # Then alter the column and tell Postgres how to cast existing strings
        op.execute("ALTER TABLE tickets ALTER COLUMN status TYPE ticketstatus USING status::ticketstatus")
    else:
        # Fallback for SQLite/others
        with op.batch_alter_table('tickets') as batch_op:
            batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticketstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.alter_column('tickets', 'status',
               existing_type=sa.Enum('open', 'in_progress', 'resolved', 'closed', name='ticketstatus'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('tickets', 'assigned_to_user_id')
    # ### end Alembic commands ###
