"""add_webhook_secret

Revision ID: 9393326e4726
Revises: 13ee6529f798
Create Date: 2026-03-24 18:50:56.326605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9393326e4726'
down_revision: Union[str, Sequence[str], None] = '13ee6529f798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('webhook_secret', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_workspaces_webhook_secret'), 'workspaces', ['webhook_secret'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_webhook_secret'), table_name='workspaces')
    op.drop_column('workspaces', 'webhook_secret')
    # ### end Alembic commands ###
